### ISSUE TITLE
No links in disambiguation page

### ISSUE THREAD

**Issue by Cwpute** [nsh07/WikiReader#11]
I understand not having links enabled for regular pages, as to be distraction-free. But this is a problem for disambiguaton pages.
For example, search for `slips` and you'll end up on a page that should provide links to other ones with the same name, but it doesn't, which makes searching for an ambiguous name quite the hassle.

Please allow links to be shown at least on disambiguation pages.

**Comment by nsh07** [comment]
Great idea, and it should be simple to implement. I'll work on it

**Comment by nsh07** [comment]
Actually, it seems this is *not* as easy to implement as it at first seems. Parsing the page text is quite easy, you can just start a link with a new line and stop the link when you reach a comma, which is the standard format for Wikipedia disambiguation pages.

But the real problem is actually incorporating this link logic to call the search function. I am putting this on hold currently, and I will get back to it after I've implemented a settings menu

**Comment by nsh07** [comment]
Hey, I've implemented this feature, although in a different manner than usual. Here's a screenshot:

![Screenshot_20241119_082839](https://github.com/user-attachments/assets/7902d39d-a26d-4f74-aeeb-80c55209d693)

I'd like to hear your opinion on this design :)

**Comment by Cwpute** [comment]
I don't like it :/ links being represented as pills like that makes the page very busy, something i don't associate with Wikireader.
A plain dots-list like you can find on Wikipedia is fine, and doesn't get-in the way of your research.

**Comment by nsh07** [comment]
Hmm :/ I guess I'll implement something like the lists on Wikipedia then.

What's the main issue with this layout though? The collage-like arrangement or the pill buttons?

**Comment by Cwpute** [comment]
Yes, it's the arrangement that i find unsatisfactory.
The lists on Wikipedia are alphabetically ordered so you can easily find what you're looking for. Putting the links next to each others in pills like that defeats that purpose.

And as much as information density can be a good goal to aim for, i'm not sure it's suitable for your app which aims to be distraction-free, as it also makes the information more noisy, less clear.

**Comment by nsh07** [comment]
> The lists on Wikipedia are alphabetically ordered so you can easily find what you're looking for

They're not alphabetically sorted, actually

![Screenshot_20241119_182958_Chrome.jpg](https://github.com/user-attachments/assets/879eac9f-340b-41f7-9f11-d4b97c28c4f3)

But that's besides the point, I get what you mean. The thing is that implementing hyperlinked text is a bit difficult so I'll have to find another way, or maybe I'll just implement hyperlinked text anyway

**Comment by nsh07** [comment]
So I actually managed to implement hyperlinks, and apparently it isn't difficult at all 😅

![Screenshot_20241119_202927](https://github.com/user-attachments/assets/6dd98fd9-4cce-4660-bca8-86ecb53d62c3)

How does it look? I'll also make it look like a bulleted list like on the website in an upcoming change
