### ISSUE TITLE
Add sepia theme 

### ISSUE THREAD

**Issue by Akshaythorat376** [nsh07/WikiReader#21]
Please add sepia and dark sepia themes to the app. I think it is a fair request, because sepia theme is offered as standard in almost all apps that require reading long texts.

**Comment by nsh07** [comment]
I'm thinking of implementing a theme color picker, something like this:

![Screenshot_20241108_204051_Auxio.jpg](https://github.com/user-attachments/assets/4aee9e8b-67b9-4b44-8f95-af4000f4bbff)

Does this look ok?

**Comment by Akshaythorat376** [comment]
Yeah, that looks good.

**Comment by shuvashish76** [comment]
Why these specific color sets? This is from material design guidelines or something?
Why not use sonething like https://github.com/skydoves/ColorPickerView or https://github.com/Dhaval2404/ColorPicker and give user the freedom to choose whatever color they like?

**Comment by Akshaythorat376** [comment]
Yeah,that will be great.just take care that colour of the text changes
accordingly to maintain contrast.

**Comment by nsh07** [comment]
@shuvashish76

> Why these specific color sets? This is from material design guidelines or something?

The material guidelines don't enforce a particular color, you can create a palette from whichever color you like. However, this set of colors seems to contain all the basic colors that you could choose (that is a screenshot from this app: https://github.com/OxygenCobalt/Auxio) and it seems to be just perfect for a custom theme picker

> Why not use sonething like https://github.com/skydoves/ColorPickerView or https://github.com/Dhaval2404/ColorPicker and give user the freedom to choose whatever color they like?

I feel like providing an entire color wheel for just the basic purpose of choosing a theme for a reading app is a bit too excessive. A few colors that cover the entire color range seems to be enough for an app like this IMO

@Akshaythorat376

> just take care that colour of the text changes accordingly to maintain contrast

Material color palette magic will take care of that 😉

**Comment by shuvashish76** [comment]
> I feel like providing an entire color wheel for just the basic purpose of choosing a theme for a reading app is a bit too excessive. A few colors that cover the entire color range seems to be enough for an app like this IMO

Yes agree, there are unlimited ways to customize the app...that doesn't mean we should add everything. Your proposal best for most use-cases especially for such simple app like this :)

**Comment by nsh07** [comment]
I've implemented this, probably will publish a new release soon. This is how it looks:

![Screenshot_20241114_115043](https://github.com/user-attachments/assets/f302bb39-fd51-4763-b91e-eefbd750bba2)

The background color for the yellow theme is still a bit too white so I'll add a separate sepia theme as well

**Comment by Akshaythorat376** [comment]
Awesome, thanks for the update!

**Comment by nsh07** [comment]
Done in v1.7.0
