### ISSUE TITLE
Feature about languages

### ISSUE THREAD

**Issue by Interleace** [nsh07/WikiReader#23]
Search for articles in different written in different languages.
Maybe a simple lang switch for languages one choosed to switch between.

For example:
I want ti read articles in German and English.
I choose both languages in settings.
Now I can toggle (or cycle, or choose).
Now, when searching for "Katze" the app shows the german article about cats, and vice versa.

Additionally, when for example the language is English and I searchfor "Katze", I get the English article for cat.
This could also be toggled in settings.

The feature above is more important because right now one can look up articles only in english (?).

(I would like to help but I write Java only! ^^)

**Comment by nsh07** [comment]
Actually it seems this should be rather simple to implement. I will work on it.

**Comment by nsh07** [comment]
Hey, I'm implementing this feature for the next update. Is something like the Wikipedia mobile website okay?

![image](https://github.com/user-attachments/assets/6e187b38-ee0d-466b-a6c8-040d1bdfa842)

I will add a language switch similar to the above screenshot to the top of the article, and you would be able to switch page language using it

**Comment by nsh07** [comment]
This is what it currently looks like

![Screenshot_20241203_185308](https://github.com/user-attachments/assets/cca01f1d-03cb-4f51-8787-021f992fbdba)
![Screenshot_20241203_185451](https://github.com/user-attachments/assets/e938e640-ed2e-44e8-937c-113d4018e25e)
![Screenshot_20241203_185651](https://github.com/user-attachments/assets/6b301b7a-6300-4122-a14a-f4a062bd41df)

I will also add a search bar to the language menus for easily switching languages

**Comment by nsh07** [comment]
Actually the button isn't persistent, it disappears when you scroll so the reading area is not compromised :)
