### ISSUE TITLE
F-Droid Release

### ISSUE THREAD

**Issue by nsh07** [nsh07/WikiReader#4]
Prepare the app for being released on the F-Droid app store

**Comment by nsh07** [comment]
Will also release it on the Google Play Store within a few weeks, when I consider this app to be polished enough

**Comment by IzzySoft** [comment]
Is any metadata (e.g. a more detailed app description) available? Especially interesting detail would be if the app is supposed to work offline (after downloading the articles maybe) or requires an internet permission to work. I see a few screenshots and an icon are already available, so given the description I could establish your app in the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid) and, if you like, provide you with the Fastlane structures needed by F-Droid via PR. Ah, wait, you already have that in the `dev` branch – OK, if you give me a ping once they've reached `main` I can look into it :wink:

**Comment by nsh07** [comment]
@IzzySoft oh man didn't expect to suddenly see you here! I would really appreciate it if you would add this to your IzzyOnDroid repo! I had thought of merging it to main today and also make a new release, but couldn't due to a lack of free time.

I will ping you tomorrow once I've merged this.

**Comment by nsh07** [comment]
@IzzySoft oh man didn't expect to suddenly see you here! I would really appreciate it if you would add this to your IzzyOnDroid repo! I had thought of merging it to main today and also make a new release, but couldn't due to a lack of free time.

I will ping you tomorrow once I've merged this.

P.S. there currently isn't any offline article saving feature in this app, even the search history isn't persistently stored. But I will soon implement both of those features.

**Comment by nsh07** [comment]
I'm thinking of renaming this app and repo, because there seems to already be a device with the [exact same name as this project](https://en.wikipedia.org/wiki/WikiReader). Will inform you once everything is done.

**Comment by IzzySoft** [comment]
> didn't expect to suddenly see you here!

Hehe, I'm showing up at the most unexpected times, huh? Have my agents out there to report to me, so i can do that :rofl:

As for that device: discontinued 10 years ago – but yeah, I get it, can be confusing.

> Will inform you once everything is done.

Cool, just give me a ping here :hugs: Looking forward to that!

**Comment by nsh07** [comment]
Hey @IzzySoft I've merged the metadata commit to main, you can add it to your repo now if you wish.

I've also forked the F-Droid data repo to add my app to the main F-Droid repo

**Comment by IzzySoft** [comment]
Thanks! Adding it now. While processing it, our scanners reported:

```
SigningBlock blobs:
-------------------
0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

Can you please take care for that? Easily done with a minor addition to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

Meanwhile, I've integrated your app at IzzyOnDroid – so it will [show up here](https://apt.izzysoft.de/packages/org.nsh07.wikireader) with the next sync around 6 pm UTC. Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme :smiley:

----

At IzzyOnDroid we support [Reproducible Builds](https://reproducible-builds.org/) (see: [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)). Trying for yours, I was able to successfully generate the APK using `./gradlew assembleRelease`, but the resulting APKs were not identical. Was that APK really built from a clean tree at the commit the tag points to? If so, did I miss some build options? How do you build the app? According to the embedded commit hash, it was built from the correct commit, but was the tree clean?

```
  -rw-r--r--  0.0 unx      120 b-      118 defN 1981-01-01 01:01:02 97992fef META-INF/version-control-info.textproto
- -rw-r--r--  0.0 unx     7957 b-     7957 stor 1981-01-01 01:01:02 0343cc64 assets/dexopt/baseline.prof
+ -rw-r--r--  0.0 unx     7957 b-     7957 stor 1981-01-01 01:01:02 f8372850 assets/dexopt/baseline.prof
  -rw-r--r--  0.0 unx      549 b-      549 stor 1981-01-01 01:01:02 15096e44 assets/dexopt/baseline.profm
  -rw-r--r--  0.0 unx 13561656 b-  4601470 defN 1981-01-01 01:01:02 8cfade30 classes.dex
- -rw-r--r--  0.0 unx  6940496 b-  2441348 defN 1981-01-01 01:01:02 e4581afb classes2.dex
+ -rw-r--r--  0.0 unx  6939692 b-  2440674 defN 1981-01-01 01:01:02 5ed11e98 classes2.dex
  -rw-r--r--  0.0 unx    10096 b-    10096 stor 1981-01-01 01:01:02 9734baa0 lib/arm64-v8a/libandroidx.graphics.path.so
```

I've checked the DEX diff, but it is HUGE (~72 kB): [dexdiff.zip](https://github.com/user-attachments/files/17460515/dexdiff.zip)

We'd appreciate if you could help making your build reproducible. We've prepared some [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) for that.

**Comment by IzzySoft** [comment]
Thanks! But sorry for having caused a misunderstanding: 9dbcb8794b9c1cc55c9998728a5c0a3cd6063fe1 does NOT enable reproducible builds, it just makes sure that signature blob is not included. For enabling RB, we need to tackle the issue with the `classes2.dex`. So for starters, could you let me know how you build your APK: on what OS, which JDK etc?

**Comment by nsh07** [comment]
Ah, I'm sorry for the mistake.

I'm building my app on Fedora Linux, with Android Studio Ladybug. I'm using the default build system on Android Studio. I'm new to Android app development (only doing this since 2 months) so I'm not very familiar with the Gradle build system.

Let me know if you need any more details, and thanks for the help!

**Comment by IzzySoft** [comment]
Thanks for the details, @nsh07! OK, so you're also building on Linux (not Windows); that mostly rules out the OS (Fedora sometimes has an issue with zlib as they're using zlib-ng instead, but that is not the culprit here or the uncompressed `classes2.dex` would be identical and just the compression would differ.

Not sure what settings/optimizations Studio is applying. Could you try building from commandline (change into the project root and run `./gradlew assembleRelease`)? If that's possible, please do so, and attach the resulting APK here (just **rename** it to `*.zip` so Github allows you to attach it), and let me know what commit you built from. I can then check if that does the trick. Depending on the results, we can see what to do.

Oh, and please make sure to build from a clean tree – so no local changes or cached stuff from previous runs. Those are often the cause of such issues. Which reminds me: did you run `clean` in Android Studio before running `build`? If not, that could be the cause as well, as AS would re-use artifacts from previous builds.

**Comment by nsh07** [comment]
Ah, I did build this thing a while ago on Windows, and never cleaned afterwards.

Here's a clean build built on Linux:
[app-release.zip](https://github.com/user-attachments/files/17470675/app-release.zip)

**Comment by IzzySoft** [comment]
Built from 6721365843d342b11b66fb007285f56bbf56a376 I guess? You didn't say, but according to the failed RB when specifying v1.3.1:

```diff
     XML ELEM START [lineno=2, name='manifest', #attributes=7]
-      ATTR: http://schemas.android.com/apk/res/android:versionCode=7
-      ATTR: http://schemas.android.com/apk/res/android:versionName='1.3.2'
+      ATTR: http://schemas.android.com/apk/res/android:versionCode=6
+      ATTR: http://schemas.android.com/apk/res/android:versionName='1.3.1'
       ATTR: http://schemas.android.com/apk/res/android:compileSdkVersion=35
```

I conclude it must be that (diff is from the `AndroidManifest.xml`). Unfortunaely, building from that commit is not RB either – but differs even more. So what did you build that APK from?

But well, I see v1.3.1 is already there, and has an APK attached. So let's give that a … success! :partying_face: That seems to be RB. Let me cleanup the recipe and give it a final run… Yes! So [here's your welcome toot](https://floss.social/@IzzyOnDroid/113353821274917837):

![image](https://github.com/user-attachments/assets/57337adb-172c-43c4-b20d-86552cefdd2a)

Thanks for your work on this! The green shield is up now.

**Comment by nsh07** [comment]
Thanks!

Now that I think about it I think I accidentally sent you a freshly built *testing apk* that Android Studio generates when you press the run button and not a proper signed apk 😅 but anyway thank you so much for all the help :)

**Comment by shuvashish76** [comment]
I think the app requires [TetheredNet](https://f-droid.org/en/docs/Anti-Features/#TetheredNet) Anti-Feature for both F-Droid and IzzyOnDroid. Wikipedia's [official app](https://f-droid.org/en/packages/org.wikipedia/) has the same AF on F-Droid.

**Comment by IzzySoft** [comment]
Good point! Especially as it works online only (at least currently), this absolutely makes sense. Added at IoD, effective with the net sync.

**Comment by nsh07** [comment]
App is now available on the F-Droid data repository (https://gitlab.com/fdroid/fdroiddata/-/merge_requests/16068)

It should be available on F-Droid within a week
