### ISSUE TITLE
Confusing color scheme entry

### ISSUE THREAD

**Issue by cirnoe** [nsh07/WikiReader#45]
The color picker, along preset pallettes, also has a "Dynamic" entry, which is represented by a white circle. I propose adding a magic wand icon over the circle to make it clearer that this is a dynamic scheme, and not white.

**Comment by nsh07** [comment]
Nice idea. I was confused about how I should make it look like it is the dynamic theme option.

Will implement in the next release. I'm on a break from this app's development right now, so it might take a few weeks. Thanks!
