### ISSUE TITLE
Missing article sections

### ISSUE THREAD

**Issue by cirnoe** [nsh07/WikiReader#46]
As of a recent update, instead of not showing any content within some of the sections, the sections are outright omitted. This can be seen on, for example, the page for hydrangea: [https://en.wikipedia.org/wiki/Hydrangea](url). Here, "Partial list of species", "Gallery" and others are missing in the app.

**Comment by nsh07** [comment]
Yeah, this is intended. The app purposefully omits empty sections and sections like "External sources" which link to external sites. 

Having sections that don't display anything can confuse the user and can also be unnecessary (such as in the case of "Gallery", if the app only displays 1 image, what's the point of even having a Gallery section?)

Also, I am planning on working on adding support for lists, tables and equations (#25, #24)

If you think empty sections should exist, do leave a reply below with why you think so. Thanks!

**Comment by cirnoe** [comment]
Ah, I did not see those issues. This is a duplicate.

**Comment by nsh07** [comment]
No problem! :)
