### ISSUE TITLE
App crashing when I click on the text/result

### ISSUE THREAD

**Issue by talha5758** [nsh07/WikiReader#8]
Also searching suggestions doesn't appear.

**Comment by nsh07** [comment]
Can you attach a video of the issue? Thanks!

**Comment by talha5758** [comment]
@nsh07 I can't semd it as video right now but I can send screenshots of it ![Screenshot_2024-10-22-10-19-52-41_b315a416a476f0a63f3f279419fb5c93.jpg](https://github.com/user-attachments/assets/f096010d-15e8-4015-aa50-4869ce3a27fd)

![Screenshot_2024-10-22-10-20-45-90_b315a416a476f0a63f3f279419fb5c93.jpg](https://github.com/user-attachments/assets/9932369e-e005-4e89-aed9-33fc7519f744)

On the second one, when I click on it, the app crashes, it is probably because there is no page for it on Wikipedia itself but it's on the Wikipedia Dictionary

**Comment by nsh07** [comment]
Yeah, I'm also experiencing a crash here. Will fix this in the next update.

**Comment by nsh07** [comment]
Fixed in v1.3.3, will get updated on IzzyOnDroid soon (possibly today)
